name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Debug SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "SSH connection successful"
      shell: bash

    - name: Backup existing deployment
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        if [ -d "/home/${{ secrets.EC2_USER }}/app" ]; then
          mv /home/${{ secrets.EC2_USER }}/app /home/${{ secrets.EC2_USER }}/app_backup_$(date +%Y%m%d%H%M%S)
        fi
        EOF
      shell: bash

    - name: Create directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'mkdir -p /home/${{ secrets.EC2_USER }}/app'

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app
      shell: bash

    - name: Deploy application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/${{ secrets.EC2_USER }}/app
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3.12-venv
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        sudo pkill -f "uvicorn" || true
        nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 &
        EOF
      shell: bash
